config:
  # Running mode
  #
  # - download: default mode, monitor URL and download when available
  # - metadata: download JSON metadata only
  # - notifier: only send notifications
  mode: download

  # Output directory
  # There's no need to quote or escape your path, examples:
  #
  # - ~/Downloads
  # - ~/Files/VTuber Videos
  # - ~/My Videos/Live Recordings
  #
  # All examples above should work
  output: ~/Downloads/VTuber Recordings

  # Loop interval, unit: second
  # Default: 10.
  interval: 10

  # Skip dependency check
  # Default: false
  skip_check: false

  # Skip converting TS file to MP4. This can save your time on lowend machines
  # Default: false
  skip_convert: false

  # Skip embedding metadata in videos.
  # Default: false
  skip_metadata: false

  # Skip sending emails when live starts/ends
  # Default: false
  skip_email: false

  # Skip sending Slack notifications when live starts
  # Default: false
  skip_slack: false

  # Skip sending notifications to specific Telegram channels (if available) when live starts
  # Default: false
  skip_telegram: false

  # Run script only once without monitoring
  # Default: false
  one_time: false

  # Set timezone for notifications
  # Default: Asia/Tokyo
  timezone: Asia/Tokyo

  # Filter video titles. Only works with channel URL in stream download mode
  #
  # - Can be single string or regex expression. ie. ASMR|歌
  # - Can be overrided by passing --filter option
  #
  # Default: "" (download all streams)
  filter: ""

  # Use youtube-dl to handle livestreams instead of streamlink
  # Default: false
  ytdl_stream: false

  # Passing additional options to youtube-dl. options should be quoted
  # Default: ""
  ytdl_args: ""

  # Passing additional options to streamlink. options should be quoted
  # Default: ""
  streamlink_args: ""

  # Choose your email provider. I recommend AWS SES
  # Default: ses
  email_provider: ses
  mailgun:
    # Find your private API key at https://app.mailgun.com/app/account/security/api_keys
    api: key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  ses:
    access: AKxxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    domain: mail.example.com
    receipt: me@example.com
  slack:
    # Create your webhook at https://slack.com/apps/A0F7XDUAZ-incoming-webhooks
    webhook: https://hooks.slack.com/services/
  telegram:
    # Obtian your bot API from @BotFather
    bot: 000000000:xxxxxxxxx
    # Get channel ID via:
    # https://api.telegram.org/bot<API-access-token>/getUpdates?offset=0
    channel: 0000000000000

# Define your own channel map.
# Channel map can provide channel specific options
map:
  - name: Sparanoid
    mode: monitor
    youtube: https://www.youtube.com/channel/UCxRuOqAAVo-f516Gygjh_wA
    bilibili: https://live.bilibili.com/456117
    telegram: -1001437419680
    timezone: America/Los_Angeles

  - name: 湊あくあ
    mode: monitor
    twitter: minatoaqua
    youtube: https://www.youtube.com/channel/UC1opHUrw8rvnsadT-iGp7Cg
    bilibili: https://live.bilibili.com/14917277
    telegram: -1001452928607
    tiktok: minatoaqua

  - name: 神楽めあ
    mode: monitor
    twitter: kaguramea_vov
    youtube: https://www.youtube.com/channel/UCWCc8tO-uUl_7SJXIKJACMw
    bilibili: https://live.bilibili.com/12235923
    twitcasting: kaguramea_vov
    openrec: KaguraMea
    telegram: -1001453708263

  - name: めあちゃんねるっ!
    youtube: https://www.youtube.com/channel/UCu5eCcfs67GkeCFbhsMrEjA
    telegram: -1001453708263

  - name: 水科葵
    youtube: https://www.youtube.com/channel/UCVFpIqGoTmFaoMmyFPRYrKA
    telegram: -1001427508895

  - name: 潤羽るしあ
    mode: monitor
    youtube: https://www.youtube.com/channel/UCl_gCybOJRIgOXw6Qb4qJzQ
    telegram: -1001448291041

  - name: 白百合リリィ
    mode: monitor
    youtube: https://www.youtube.com/channel/UCl-3q6t6zdZwgIsFZELb7Zg
    telegram: -1001437419680

  - name: 百鬼あやめ
    youtube: https://www.youtube.com/channel/UC7fk0CB07ly8oSl0aqKkqFg
    telegram: -1001437419680

  - name: 白上フブキ
    mode: monitor
    youtube: https://www.youtube.com/channel/UCdn5BQ06XqgXoAxIhbqw5Rg
    telegram: -1001396390139

  - name: 有栖マナ
    youtube: https://www.youtube.com/channel/UCIaC5td9nGG6JeKllWLwFLA
    bilibili: https://space.bilibili.com/3149619
    twitch: https://www.twitch.tv/alicemana_v

  - name: 音俣るか
    youtube: https://www.youtube.com/channel/UCNSr_pgMH3in2d0RGtcdEEg
    bilibili: https://space.bilibili.com/406548031

  - name: 物述有栖
    youtube: https://www.youtube.com/channel/UCt0clH12Xk1-Ej5PXKGfdPA
    bilibili: https://space.bilibili.com/434565011

  - name: 宗谷いちか
    youtube: https://www.youtube.com/channel/UC2kyQhzGOB-JPgcQX9OMgEw

  - name: 癒月ちょこ
    youtube: https://www.youtube.com/channel/UC1suqwovbL1kzsoaZgFZLKg

  - name: 乙女おと
    youtube: https://www.youtube.com/channel/UCvEX2UICvFAa_T6pqizC20g

  - name: 天宮こころ
    youtube: https://www.youtube.com/channel/UCkIimWZ9gBJRamKF0rmPU8w

  - name: 夜空メルチャンネル
    youtube: https://www.youtube.com/channel/UCD8HOxPs4Xvsm8H0ZxXGiBw

  - name: かぐらなな
    youtube: https://www.youtube.com/channel/UCbfv8uuUXt3RSJGEwxny5Rw

  - name: 赤井はあと
    youtube: https://www.youtube.com/channel/UC1CfXB_kRs3C-zaeTG3oGyg
    telegram: -1001437419680

  - name: 笹木咲
    youtube: https://www.youtube.com/channel/UCoztvTULBYd3WmStqYeoHcA
    telegram: -1001437419680

  - name: 不知火フレア
    youtube: https://www.youtube.com/channel/UCvInZx9h3jC2JzsIzoOebWg

  - name: 樋口楓
    youtube: https://www.youtube.com/channel/UCsg-YqdqQ-KFF0LNk23BY4A

  - name: 美波七海
    youtube: https://www.youtube.com/channel/UCrwJvtphcyux30pAgoX68jA
